#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
~/.config/polybar/launch.sh &
nitrogen --restore

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          10
bspc config normal_border_color "#83a598" #light blue
#bspc config active_border_color "#458588" #blue
bspc config focused_border_color "#d65d0e" #orange
bspc config presel-feedback_color "#d79921" #yellow


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
